"""Create Estates table

Revision ID: 247c7a29c0fc
Revises: 4155f8999f75
Create Date: 2024-01-03 16:13:40.501235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247c7a29c0fc'
down_revision: Union[str, None] = '4155f8999f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Use the 'Estates' table name
table_name = 'estates'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        table_name,
        sa.Column('ID', sa.Integer(), primary_key=True),
        sa.Column('Estate_Name', sa.String(), nullable=False),
        sa.Column('Estate_RV', sa.Integer(), nullable=False)
    )


def downgrade():
    op.drop_table(table_name)
    # ### end Alembic commands ###
