"""Add Estate_ID column to Blocks

Revision ID: 5258051d371c
Revises: cc60be90427b
Create Date: 2024-01-10 16:32:10.359323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5258051d371c'
down_revision: Union[str, None] = 'cc60be90427b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('Estate_ID', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'Estate_ID')
    # ### end Alembic commands ###
