"""Create Charges table

Revision ID: cc60be90427b
Revises: 247c7a29c0fc
Create Date: 2024-01-03 16:31:07.842233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc60be90427b'
down_revision: Union[str, None] = '247c7a29c0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Use the 'Charges' table name
table_name = 'charges'

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        table_name,
        sa.Column('Year_Start', sa.Integer(), primary_key=True),
        sa.Column('Year_End', sa.Integer(), primary_key=True),
        sa.Column('Block_ID', sa.Integer(), primary_key=True),
        sa.Column('Estate_ID', sa.Integer(), primary_key=True),
        sa.Column('Block_Boiler_Repairs_and_Maintenance', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Cleaning', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Communal_Electricity', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Communal_Electrical_Maintenance', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Communal_Ventilation_Maintenance', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Communal_Water_Quality', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Communal_Window_Cleaning', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Concierge', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_CCTV', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Disinfestation', sa.Numeric(precision=10, scale=2)),
        sa.Column('Block_Door_Entry_System', sa.Numeric(precision=10, scale=2)),
        sa.Column('Estate_Cleaning', sa.Numeric(precision=10, scale=2)),
        sa.Column('Estate_CCTV', sa.Numeric(precision=10, scale=2)),
        sa.Column('Estate_Communal_Electricity', sa.Numeric(precision=10, scale=2)),
        sa.Column('Estate_Grounds_Maintenance', sa.Numeric(precision=10, scale=2)),
        sa.Column('Estate_Repairs_and_Maintenance', sa.Numeric(precision=10, scale=2)),
        sa.Column('Estate_Tree_Maintenance', sa.Numeric(precision=10, scale=2))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(table_name)
    # ### end Alembic commands ###
